export YTT_TAS_system_registry__hostname="registry.pivotal.io"
export YTT_TAS_system_registry__username="USERID"
export YTT_TAS_system_registry__password="PASSWORD"
export YTT_TAS_app_registry__hostname="harbor.<YOUR-DOMAIN>"
export YTT_TAS_app_registry__repository="harbor.<YOUR-DOMAIN>/tas-workloads"
export YTT_TAS_app_registry__username="admin"
export YTT_TAS_app_registry__password="<HARBOR-PASSWORD>"
