kind: StorageClass
# https://kubernetes.io/docs/concepts/storage/storage-classes/#aws-ebs
apiVersion: storage.k8s.io/v1
metadata:
  name: aws
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  labels:
    type: aws
    storage: small
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
reclaimPolicy: Delete
mountOptions:
  - debug
volumeBindingMode: Immediate
